--- 
- hosts: javaserver
  become: yes
  tasks:
      - name : i want to run linux command
        command: hostname -f
        register: myresult

      - name: i want to display linux command output value
        debug:
           msg: "{{myresult}}"

      - name: i want to install apache2
        apt:
           name: apache2
           state: present

      