--- 
- hosts: javaserver
  become: yes
 
  tasks:    
      - name: i want to install packages through loop
        apt:
            name: "{{item}}"
            state: present
        loop: 
         - git
         - tree
         - nginx